### ISSUE TITLE
Design a landing page

### ISSUE THREAD

**Issue by just-be-dev** [vuenyc/vuenyc.github.io#1]

**Comment by gabytabs** [comment]
@zhangoose

**Comment by zhangoose** [comment]
@gabytabs .... what?

**Comment by gabytabs** [comment]
@zhangoose the `gomoku bird and horse` LGTM, probably you want to design the VueNYC landing page as well... maybe? perhaps? please?

**Comment by just-be-dev** [comment]
😄 I don't think it has to be very complicated. Could use some extra ideas though because I suck at design.

**Comment by zhangoose** [comment]
a picture of a bunch of buildings whose ceilings together draw out a V

**Comment by gabytabs** [comment]
I guess that's a good start as a header. :)
we could add some stars as well, with this `http://vincentgarreau.com/particles.js/#nasa`.

**Comment by gabytabs** [comment]
I am assuming it is night time. trololo.

**Comment by zhangoose** [comment]
idk, i like how it is right now though. just simple and to the point.
